[package]
name = "wynd-utils"
version = "1.2.0"
authors = ["Cosmorama <cosmorama@proton.me>"]
license = "Apache-2.0"
description = "Utility functions used by multiple Wynd contracts"
edition = "2021"

[dependencies]
cosmwasm-std = "1.1"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }

[dev-dependencies]
cw-storage-plus = "0.15"
prost = "0.9"
cw-multi-test = "0.15"
test-case = "2.1.0"
